#!/usr/bin/env bash

# Managing
alias npm-list-global="npm list -g --depth=0"
alias npm-prune="npm cache clean \$(npm config get cache) && rm node_modules"
alias npm-prune-reinstall="npm cache clear && rm node_modules && npm install"

# Run tasks
alias nrb="npm run build || npm run dist || npm run production"
alias nrd="npm run development || npm run develop || npm run dev"
alias nrs="npm run serve"

# Check for outdated dependencies
function npmo() {
  if which npm-check >/dev/null; then
    npm-check -u -E
  else
    npm outdated
  fi
}
